### ISSUE TITLE
Stork agent - app detection model

### ISSUE THREAD

**Issue by ymartin-ovh** [isc-projects/stork#5]
Hello

I wanted to run stork agent to use the nice work done on the prometheus side of this daemon.
On hardened systems, I can't process.Process() does not return named process to stork-agent.

An alternative to the whole detection mechanism is to have the ability to pass statistic channel endpoint (ip, port), eventually control channel with command line or configuration file.
With that, the daemon could run on different user id or different system for example or on pod different from bind9 pod in a kubernetes deployment.

Regards

**Comment by tomaszmrugalski** [comment]
That sounds like a very reasonable feature request. There's some related work to improve the detection routine (see [stork#474](https://gitlab.isc.org/isc-projects/stork/-/issues/474) and the alternative was [specifically discussed here](https://gitlab.isc.org/isc-projects/stork/-/merge_requests/280#note_206168). I'd love to get your thoughts on this, as the devs talked about the topic and couldn't reach a consensus.

I'd love to continue this discussion on gitlab. I'd appreciate a lot if you could open this ticket again on the [main Stork repo](https://gitlab.isc.org/isc-projects/stork). Thanks!

I'm closing this issue, because we're shutting down the issue tracker on github.

**Comment by ymartin-ovh** [comment]
Ok, I create https://gitlab.isc.org/isc-projects/stork/-/issues/535
